let isDone: boolean = false; //boolean
let decimal: number = 6; //number
let hex: number = 0xf00d; //number
let binary: number = 0b1010; //number
let octal: number = 0o744; //number
let color: string = "blue"; //string
let numbersList: number[] = [1, 2, 3]; //array with numbers
let stringsList: string[] = ["Balu", "Bagirakaa", "kaa"]; //array with strings
let notTypedList: any[] = [1, true, "free"];
